import Head from 'next/head'
import Image from 'next/image'

import { CalendarSyncWrapper } from '../components/CalendarSyncWrapper'

import styles from '../styles/Home.module.css'

export default function Home() {
  const calendarSyncOptions = {
    target_id: "cronofy-calendar-sync",
    authorization: {
      redirect_uri: "https://example.org/oauth/redirect",
      client_id: "XXX",
      scope: "read_only"
    },
    styles: {
      prefix: "CalendarSync"
    },
    demo: true
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <CalendarSyncWrapper options={calendarSyncOptions} />
      </main>
    </div>
  )
}
